version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      # As variáveis agora são lidas do arquivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # A API também lê as mesmas variáveis do arquivo .env
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      # A URL do banco também pode ser construída com variáveis
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}

volumes:
  postgres_data: