
version: '3.8'

services:

  db:

    image: postgres:14-alpine

    restart: always

    environment:
      POSTGRES_USER: new_user      # IMPORTANTE: Use o mesmo usuário do seu application.properties
      POSTGRES_PASSWORD: my_pwd    # IMPORTANTE: Use a mesma senha do seu application.properties
      POSTGRES_DB: postgres      # IMPORTANTE: Use o mesmo nome de banco do seu application.properties

    
    ports:
      - "5432:5432"

    
    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build: .  
    ports:
      - "8080:8080"
    environment:
     
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres # IMPORTANTE: Use o mesmo usuário do seu application.properties
      SPRING_DATASOURCE_USERNAME: new_user # IMPORTANTE: Use a mesma senha do seu application.properties
      SPRING_DATASOURCE_PASSWORD: my_pwd # IMPORTANTE: Use o mesmo nome de banco do seu application.properties
    depends_on:
      - db 
volumes:
  postgres_data:
